<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Style-Type" content="text/css" />
        <meta http-equiv="Content-Script-Type" content="application/javascript" />
        
        <? if (IS_WORKSPACE): ?>
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="pragma" content="no-cache" />
        <? endif; ?>
        
        <meta name="description" content=" " />
        <meta name="keywords" content=" " />
        <meta name="author" content=" " />
        
        <title><?= $title ?></title>
        
        <!--<link rel="shortcut icon" href="<?= $project_host ?>favicon.ico">-->
        
        <? foreach ($cssFiles AS $file): ?>
            <link rel="stylesheet" type="text/css" href="<?= $file ?>" />
        <? endforeach; ?>
        
        <? foreach ($jsFiles AS $file): ?>
            <script type="application/javascript" src="<?= $file ?>" ></script>
        <? endforeach; ?>
    </head>
    
    <body>
        
        <?= $content ?>

    </body>
</html>