<!DOCTYPE html>
<html>
    <head>
        <base href="<?= $project_host ?>">
        
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Style-Type" content="text/css" />
        <meta http-equiv="Content-Script-Type" content="application/javascript" />
        
        <? if (IS_WORKSPACE): ?>
        <meta http-equiv="cache-control" content="no-cache" />
        <meta http-equiv="pragma" content="no-cache" />
        <? endif; ?>
        
        <meta name="description" content=" " />
        <meta name="keywords" content=" " />
        <meta name="author" content=" " />
        
        <title><?= $title ?></title>
        
        <link rel="shortcut icon" href="<?= $project_host ?>favicon.ico">
        <?= helpers\Assets::draw() ?>
        
        <script type="text/javascript">
            var project_host = "<?= $project_host ?>";
        </script>
    </head>
    
    <body>
        
        <?= $content ?>

    </body>
</html>